Search for docs in default location (relative to REGISTRY_HOME) if there is no solr-docs parameter

diff --git a/src/main/resources/bin/search-post b/src/main/resources/bin/search-post
--- a/src/main/resources/bin/search-post
+++ b/src/main/resources/bin/search-post
@@ -42,19 +42,17 @@ TOOL_JAR=(${LIB_DIR}/solr-core-*.jar)
 
 function print_usage() {
   echo ""
-  echo "Usage: $0 [OPTIONS] <file|directory>"
+  echo "Usage: $0 [OPTIONS] [SOLR-DOCS]"
   echo ""
   echo "Options:"
-  echo "  -host <host> (default: localhost)"
-  echo "  -port <port> (default: 8983)"
+  echo "  -h            Print Help"
+  echo "  -host <host>  Solr server host (default: localhost)"
+  echo "  -port <port>  Solr server port (default: 8983)"
+  echo ""
+  echo "Optional Parameters:"
+  echo "  SOLR-DOCS     solr-docs directory or an xml file"
   echo ""
 }
-
-# Check number of command line parameters
-if [[ $# -eq 0 ]]; then
-  print_usage
-  exit
-fi
 
 # Parse command line parameters
 while [ $# -gt 0 ]; do
@@ -66,17 +64,15 @@ while [ $# -gt 0 ]; do
     # File
     FILES+=("$1")
   else
-    if [[ "$1" == -* ]]; then
-      if [[ "$1" == "-port" ]]; then
-        shift
-        PROPS+=("-Dport=$1")
-      elif [[ "$1" == "-host" ]]; then
-        shift
-        PROPS+=("-Dhost=$1")
-      else
-        echo -e "\nUnrecognized argument: $1\n"
-        exit 1
-      fi
+    if [[ "$1" == "-port" ]]; then
+      shift
+      PROPS+=("-Dport=$1")
+    elif [[ "$1" == "-host" ]]; then
+      shift
+      PROPS+=("-Dhost=$1")
+    elif [[ "$1" == "-h" ]]; then
+      print_usage
+      exit
     else
       echo -e "\nUnrecognized argument: $1\n"
       exit 1
@@ -84,6 +80,44 @@ while [ $# -gt 0 ]; do
   fi
   shift
 done
+
+# No file / directory parameter
+if [[ "${#FILES[@]}" -eq 0 ]]; then
+  echo "INFO:  No SOLR-DOCS parameter (Use -h flag to print help)."
+  echo "INFO:  Looking for Solr documents in default location."
+
+  REGISTRY_HOME=${PARENT_DIR}/../registry
+  if [ ! -e "${REGISTRY_HOME}" ]; then
+    echo
+    echo "ERROR: Registry does not exist at ${REGISTRY_HOME}." 1>&2
+    echo "       Verify Registry has been installed and path is valid." 1>&2
+    echo "       If path to Registry differs, please update in this script." 1>&2
+    echo
+    exit 1
+  fi
+  # Normalize
+  REGISTRY_HOME=$(cd "${REGISTRY_HOME}" && pwd)
+
+  REGISTRY_DATA=${REGISTRY_HOME}/../registry-data/solr-docs
+  if [ ! -e "${REGISTRY_DATA}" ]; then    
+    echo
+    echo "ERROR: ${REGISTRY_DATA} does not exist as expected." 1>&2
+    echo "       Verify Registry installation completed successfully." 1>&2
+    echo
+    exit 1
+  fi
+
+  # Must be a directory
+  if [[ -d "${REGISTRY_DATA}" ]]; then
+    RECURSIVE=yes
+    FILES+=("${REGISTRY_DATA}")
+  else
+    echo "${REGISTRY_DATA} must be a directory."
+    exit 1
+  fi
+
+  echo "INFO:  Found Solr documents in ${REGISTRY_DATA}"
+fi
 
 # Setup Java
 if [ -n "$JAVA_HOME" ]; then
